services:
  # Base de Datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: asistpy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: asistpy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base de Datos MySQL
  mysql:
    image: mysql:8.4
    container_name: asistpy-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: asistpy
      MYSQL_USER: asistpy
      MYSQL_PASSWORD: asistpypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Base de Datos NoSQL MongoDB
  mongodb:
    image: mongo:7.0
    container_name: asistpy-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: asistpy
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mysql_data:
  mongo_data:
