"""Puerto AttendanceRepository para marcaciones crudas."""

from datetime import date, datetime
from typing import Protocol

from attendance.domain.device.log import AttendanceLog


class AttendanceRepository(Protocol):
    """Contrato de persistencia para marcaciones crudas y eventos de asistencia."""

    def save_raw_log(self, log: AttendanceLog) -> None: ...
    def get_unprocessed_logs(self) -> list[AttendanceLog]: ...
    def mark_as_processed(self, log_id: int, inferred_type: str) -> None: ...
    def get_by_id(self, log_id: int) -> AttendanceLog | None: ...
    def get_logs_by_employee_and_date(
        self, employee_pin: str, target_date: date
    ) -> list[AttendanceLog]: ...
    def get_logs_for_employee(
        self, employee_pin: str, start_time: datetime, end_time: datetime
    ) -> list[AttendanceLog]: ...
    def update_log(self, log: AttendanceLog) -> AttendanceLog: ...
    def list_all(self) -> list[AttendanceLog]: ...
