"""Puerto BranchRepository para persistencia y consulta de sucursales."""

from typing import Protocol

from attendance.domain.organization.branch import Branch


class BranchRepository(Protocol):
    """Contrato de persistencia y catálogo para sucursales."""

    def save(self, branch: Branch) -> Branch: ...

    def save_all(self, branches: list[Branch]) -> list[Branch]: ...

    def get_by_id(self, branch_id: int) -> Branch | None: ...

    def get_by_code(self, code: str) -> Branch | None: ...

    def get_by_name(self, name: str) -> Branch | None: ...

    def exists_by_id(self, branch_id: int) -> bool: ...

    def exists_by_code(self, code: str) -> bool: ...

    def list_all(self, active_only: bool = False) -> list[Branch]: ...

    def count(self, active_only: bool = False) -> int: ...

    def delete(self, branch_id: int) -> bool: ...

