"""Puerto EmployeeRepository para gestión de empleados."""

from typing import Protocol

from attendance.domain.organization.employee import Employee


class EmployeeRepository(Protocol):
    """Contrato de persistencia y consulta para empleados de la organización."""

    def save(self, employee: Employee) -> Employee: ...

    def save_all(self, employees: list[Employee]) -> list[Employee]: ...

    def get_by_id(self, employee_id: int) -> Employee | None: ...

    def get_by_pin(self, pin: str) -> Employee | None: ...

    def get_by_curp(self, curp: str) -> Employee | None: ...

    def get_by_rfc(self, rfc: str) -> Employee | None: ...

    def get_by_card_number(self, card_number: str) -> Employee | None: ...

    def get_by_email(self, email: str) -> Employee | None: ...

    def exists_by_pin(self, pin: str) -> bool: ...

    def exists_by_id(self, employee_id: int) -> bool: ...

    def list_all(
        self,
        branch_id: int | None = None,
        department_id: int | None = None,
        position_id: int | None = None,
        active_only: bool = False,
    ) -> list[Employee]: ...

    def list_active(self, branch_id: int | None = None) -> list[Employee]: ...

    def get_active_employees(self, branch_id: int | None = None) -> list[Employee]: ...

    def count(
        self,
        branch_id: int | None = None,
        department_id: int | None = None,
        position_id: int | None = None,
        active_only: bool = False,
    ) -> int: ...

    def delete(self, pin: str) -> bool: ...

    def delete_by_id(self, employee_id: int) -> bool: ...
